### ISSUE TITLE
Error handling response: TypeError: Cannot read property 'id' of undefined

### ISSUE THREAD

**Issue by j10sanders** [nemrosim/chrome-react-extension-example#1]
Hey, thanks for your tutorial.  I tried the tutorial and also just cloned your repo.  When I click on either button, I get an error in my console:

`Error handling response: TypeError: Cannot read property 'id' of undefined`

I also don't think the background listeners are working, because I don't see any console logging.

Thanks again

**Comment by nemrosim** [comment]
@j10sanders Yep, I don't think that all is working as expected. You are correct, background script should show you an alert notification at the start of your extension. Could you provide more info about the issue?

**Comment by nemrosim** [comment]
@j10sanders I've clone this project also, I found an issue with a logo file, but no "id" errors, all works as expected:
![2020-12-04_15-07-59](https://user-images.githubusercontent.com/22501553/101167492-a2ae3780-3642-11eb-999f-a784ad2b9561.jpg)

**Comment by nemrosim** [comment]
@j10sanders Closing issue
